name: Test Auth Service

on:
  pull_request:
    branches:
      - main
    paths:
      - 'services/auth_service/**'
      - '.github/workflows/auth_service_ci.yml'
  push:
    paths:
      - '.github/workflows/auth_service_ci.yml'
      - 'services/auth_service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/auth_service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: ls

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: services/auth_service/package-lock.json

      - name: dependencies
        run: npm ci

      - name: Run tests
        run: npm test
