on:
  workflow_run:
    workflows: ["auth_service"]
    types:
      - completed

name: Sonar
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@7
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
